# Generated by Django 4.2.5 on 2023-11-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('math_rating', models.CharField(max_length=50)),
                ('ukr_rating', models.CharField(max_length=50)),
                ('hist_rating', models.CharField(max_length=50)),
                ('selfpaying', models.BooleanField()),
            ],
        ),
    ]
