# Generated by Django 4.2.5 on 2023-11-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
